[package]
name = "redstone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lsp-types = "0.95.0"
lsp-server = "0.7.6"
anyhow = "1.0.79"
xflags = "0.3.2"
