[package]
name = "sourcegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote.workspace = true
proc-macro2.workspace = true
xshell.workspace = true
ungrammar.workspace = true
